[package]
name = "monochrome-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
aes = "0.9"
ctr = "0.10"
symphonia = { version = "0.5", features = ["all-codecs", "all-formats"] }
cpal = "0.18"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking"] }

[dev-dependencies]
tiny_http = "0.12"
