[package]
name = "monochrome-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
monochrome-core = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls-no-provider", "stream", "gzip", "query"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
url = "2"
rand = "0.10"
futures-util = { version = "0.3", default-features = false, features = ["std", "async-await"] }

[dev-dependencies]
wiremock = "0.6"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
